### ISSUE TITLE
Último nivel, colores incorrectos.

### ISSUE THREAD

**Issue by ojeelafriend** [francis62/broken11#13]
En el último nivel de colores me sale un "do" que no es el que sobra. Aquí adjunto imágenes.
![Screenshot_3](https://user-images.githubusercontent.com/63030605/169135600-e1f570f8-ed74-4535-b2ad-617a9c824742.png)

**Comment by phranb** [comment]
Estuve jugando y no tuve problemas, lo voy a revisar este fin de semana, esta es mi explicacion de lo que te paso:
Creo que perdiste, el tema es que el juego no te avisa hasta que gastes las vidas. Si te quedan 2 bloques de otro color del que te pide podes romperlos y ganar, con tres o mas es game over. Porque el "last:" o sea el ultimo color que tocaste es el que aparece en el "do". Si el color es distinto del que te pide al final, ese color ya pasó. Pero el juego te exige que toques los bloques (deberia decirte que perdiste a esta altura pero no esta programado asi)

**Comment by ojeelafriend** [comment]
Es cierto, porque estuve seleccionando sin tomar en cuenta la totalidad de los cuadrados que habían en ese momento del color indicado en el "do".  😄
